// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplitMoneyTg.Infrastructure;

#nullable disable

namespace SplitMoneyTg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920200206_ReleaseOneDatabaseHardening")]
    partial class ReleaseOneDatabaseHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SplitMoneyTg.Domain.ApiIdempotencyRecord", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Key");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("ApiIdempotencyRecords");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.AppUser", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentDetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("TelegramId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountKopecks")
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<long>("PayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "AuthorId");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.HasIndex("GroupId", "PayerId");

                    b.ToTable("Expenses", t =>
                        {
                            t.HasCheckConstraint("CK_Expenses_Amount", "\"AmountKopecks\" BETWEEN 1 AND 1000000000000");

                            t.HasCheckConstraint("CK_Expenses_Description", "length(btrim(\"Description\")) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.ExpenseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups", t =>
                        {
                            t.HasCheckConstraint("CK_Groups_Name", "length(btrim(\"Name\")) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Groups_Type", "\"Type\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.ExpenseShare", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountKopecks")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("ExpenseId", "UserId");

                    b.HasIndex("GroupId", "ExpenseId");

                    b.HasIndex("GroupId", "UserId");

                    b.ToTable("ExpenseShares", t =>
                        {
                            t.HasCheckConstraint("CK_ExpenseShares_Amount", "\"AmountKopecks\" > 0");
                        });
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.GroupParticipant", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentDetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("GroupId", "ParticipantId");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("GroupId", "TelegramUserId")
                        .IsUnique();

                    b.ToTable("GroupParticipants", t =>
                        {
                            t.HasCheckConstraint("CK_GroupParticipants_Identity", "(\"TelegramUserId\" IS NOT NULL AND \"ParticipantId\" = \"TelegramUserId\" AND \"ParticipantId\" > 0) OR (\"TelegramUserId\" IS NULL AND \"ParticipantId\" < 0 AND length(btrim(\"DisplayName\")) BETWEEN 1 AND 100)");
                        });
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP + INTERVAL '7 days'");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("GroupId", "CreatedById");

                    b.ToTable("Invitations", t =>
                        {
                            t.HasCheckConstraint("CK_Invitations_Token", "\"Token\" ~ '^[0-9a-f]{32}$'");
                        });
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.ProcessedUpdate", b =>
                {
                    b.Property<int>("UpdateId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UpdateId");

                    b.ToTable("ProcessedUpdates");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountKopecks")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "FromUserId");

                    b.HasIndex("GroupId", "Status");

                    b.HasIndex("GroupId", "ToUserId");

                    b.ToTable("Transfers", t =>
                        {
                            t.HasCheckConstraint("CK_Transfers_Amount", "\"AmountKopecks\" > 0");

                            t.HasCheckConstraint("CK_Transfers_Participants", "\"FromUserId\" <> \"ToUserId\"");

                            t.HasCheckConstraint("CK_Transfers_Resolution", "(\"Status\" = 0 AND \"ResolvedAt\" IS NULL) OR (\"Status\" IN (1, 2) AND \"ResolvedAt\" IS NOT NULL) OR \"Status\" = 3");

                            t.HasCheckConstraint("CK_Transfers_Status", "\"Status\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.UserSession", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Sessions", t =>
                        {
                            t.HasCheckConstraint("CK_Sessions_DataJson", "\"DataJson\"::jsonb IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.ApiIdempotencyRecord", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.Expense", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.ExpenseGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SplitMoneyTg.Domain.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SplitMoneyTg.Domain.GroupParticipant", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.ExpenseGroup", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.ExpenseShare", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.Expense", "Expense")
                        .WithMany("Shares")
                        .HasForeignKey("GroupId", "ExpenseId")
                        .HasPrincipalKey("GroupId", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SplitMoneyTg.Domain.GroupParticipant", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.GroupMember", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.ExpenseGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitMoneyTg.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.GroupParticipant", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.ExpenseGroup", "Group")
                        .WithMany("Participants")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitMoneyTg.Domain.AppUser", "TelegramUser")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.Invitation", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SplitMoneyTg.Domain.ExpenseGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.Transfer", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.ExpenseGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SplitMoneyTg.Domain.GroupParticipant", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SplitMoneyTg.Domain.GroupParticipant", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.UserSession", b =>
                {
                    b.HasOne("SplitMoneyTg.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.Expense", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("SplitMoneyTg.Domain.ExpenseGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
